apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grr-hpa-90cpu
spec:
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 90
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grr
