apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k6: k6-azema
  name: k6-azema
spec:
  clusterIP: None
  ports:
  - name: k6-azema
    port: 5656
    protocol: TCP
    targetPort: 5656
  selector:
    k6: k6-azema
  type: ClusterIP
status:
  loadBalancer: {}
